services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile

    container_name: app-sala-espera
    
    ports:
      - "8087:8080"
          
    restart: unless-stopped
    
    environment:
      - JAVA_OPTS=-Xmx512m
      - JAVA_TOOL_OPTIONS=-Duser.language=pt -Duser.country=BR -Dfile.encoding=UTF-8
      - TZ=America/Bahia